CREATE DATABASE Supermarket;

CREATE TABLE NHA_CUNG_CAP(
MA_CC VARCHAR(50) NOT NULL, --NCC1 NCC12--
TEN_NCC VARCHAR(50) NOT NULL,
DIA_CHI VARCHAR(50) NOT NULL,
SDT CHAR(10) NOT NULL
)

CREATE TABLE NHAN_VIEN(
MA_NV VARCHAR(50) NOT NULL, --NV1 - NV12
TEN_NV VARCHAR(50) NOT NULL,
DIA_CHI VARCHAR(50) NOT NULL
)


