CREATE DATABASE Supermarket;


CREATE TABLE NHA_CUNG_CAP(
ma_ncc VARCHAR(50) NOT NULL, /*NCC1 NCC12 */
TEN_NCC VARCHAR(50) NOT NULL,
DIA_CHI VARCHAR(50) NOT NULL,
SDT_NCC CHAR(10) NOT NULL
);

CREATE TABLE NHAN_VIEN(
ma_nv VARCHAR(50) NOT NULL, --NV1 - NV12
TEN_NV VARCHAR(50) NOT NULL,
DIA_CHI_NV VARCHAR(50) NOT NULL
);

CREATE TABLE GIAN_HANG(
stt_gh CHAR(3) NOT NULL,
TEN_GH VARCHAR(50) NOT NULL,
TRUONG_GIAN VARCHAR(50) NOT NULL
);

CREATE TABLE KHACH(
ma_kh VARCHAR(50) NOT NULL, --KH1 KH12
TEN_KH VARCHAR(50) NOT null,
DIA_CHI_KH VARCHAR(50) NOT NULL,
SDT_KH CHAR(10) NOT NULL
);

CREATE TABLE HOA_DON(
ma_hd VARCHAR(50) NOT NULL, --HD1 HD12
NGAY_LAP_HD date NOT NULL,
MA_NV_LAP VARCHAR(50) NOT NULL,
MA_KHACH_MUA VARCHAR(50) NOT NULL
);

CREATE TABLE MAT_HANG(
ma_mh VARCHAR(50) NOT NULL,
TEN_MH VARCHAR(50) NOT NULL,
GIA NUMERIC(20) NOT NULL,
MA_NCC VARCHAR(50) NOT NULL,
STT_GH CHAR(3) NULL
);

CREATE TABLE CT_HOADON(
ma_hd VARCHAR(50) NOT NULL,
MA_MH VARCHAR(50) NOT NULL,
SO_LUONG INT NULL,
GIA numeric NULL
);

ALTER TABLE NHA_CUNG_CAP ADD CONSTRAINT PK_NCC PRIMARY KEY (ma_ncc) ;
ALTER TABLE NHAN_VIEN ADD CONSTRAINT PK_NV PRIMARY KEY (ma_nv);
ALTER TABLE KHACH ADD CONSTRAINT PK_KH PRIMARY KEY (ma_kh);
ALTER TABLE GIAN_HANG ADD CONSTRAINT PK_GH PRIMARY KEY (stt_gh);
ALTER TABLE MAT_HANG ADD CONSTRAINT PK_MH PRIMARY KEY (ma_mh);
ALTER TABLE HOA_DON ADD CONSTRAINT PK_HD PRIMARY KEY (ma_hd);
ALTER TABLE CT_HOADON ADD CONSTRAINT PK_CTHD PRIMARY KEY (MA_HD, MA_MH);


ALTER TABLE GIAN_HANG ADD CONSTRAINT FK_GH_NV FOREIGN KEY (TRUONG_GIAN) REFERENCES NHAN_VIEN(MA_NV);

ALTER TABLE MAT_HANG ADD CONSTRAINT FK_MH_NCC FOREIGN KEY (MA_NCC) REFERENCES NHA_CUNG_CAP(ma_ncc);
ALTER TABLE MAT_HANG ADD CONSTRAINT FK_MH_GH FOREIGN KEY (STT_GH) REFERENCES GIAN_HANG(STT_GH);

ALTER TABLE HOA_DON ADD CONSTRAINT FK_HD_NV FOREIGN KEY (MA_NV_LAP) REFERENCES NHAN_VIEN(MA_NV);
ALTER TABLE HOA_DON ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MA_KHACH_MUA) REFERENCES KHACH(MA_KH);

ALTER TABLE CT_HOADON ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY (MA_HD) REFERENCES HOA_DON(MA_HD);
ALTER TABLE CT_HOADON ADD CONSTRAINT FK_CTHD_MH FOREIGN KEY (MA_MH) REFERENCES MAT_HANG(MA_MH);



