CREATE DATABASE Supermarket;

CREATE TABLE NHA_CUNG_CAP(
MA_NCC VARCHAR(50) NOT NULL, --NCC1 NCC12--
TEN_NCC VARCHAR(50) NOT NULL,
DIA_CHI VARCHAR(50) NOT NULL,
SDT_NCC CHAR(10) NOT NULL,
CONSTRAINT PK_NHA_CUNG_CAP PRIMARY KEY (MA_NCC)
)

CREATE TABLE NHAN_VIEN(
MA_NV VARCHAR(50) NOT NULL, --NV1 - NV12
TEN_NV VARCHAR(50) NOT NULL,
DIA_CHI_NV VARCHAR(50) NOT NULL,
CONSTRAINT PK_NHAN_VIEN  PRIMARY KEY (MA_NV)
)

CREATE TABLE GIAN_HANG(
STT_GH CHAR(3) NOT NULL,
TEN_GH VARCHAR(50) NOT NULL,
TRUONG_GIAN VARCHAR(50) NOT NULL,
CONSTRAINT PK_GIAN_HANG PRIMARY KEY (STT_GH),
CONSTRAINT FK_GIAN_HANG_NHAN_VIEN FOREIGN KEY (TRUONG_GIAN) REFERENCES NHAN_VIEN (MA_NV)
)

CREATE TABLE KHACH(
MA_KH VARCHAR(50) NOT NULL, --KH1 KH12
TEN_KH VARCHAR(50) NOT null,
DIA_CHI_KH VARCHAR(50) NOT NULL,
SDT_KH CHAR(10) NOT NULL,
CONSTRAINT PK_KHACH PRIMARY KEY (MA_KH)
)

CREATE TABLE HOA_DON(
MA_HD VARCHAR(50) NOT NULL, --HD1 HD12
NGAY_LAP_HD date NOT NULL,
MA_NV_LAP VARCHAR(50) NOT NULL,
MA_KHACH_MUA VARCHAR(50) NOT NULL,
CONSTRAINT PK_HOA_DON PRIMARY KEY (MA_HD),
CONSTRAINT FK_HOA_DON_NHAN_VIEN FOREIGN KEY (MA_NV_LAP) REFERENCES NHAN_VIEN(MA_NV),
CONSTRAINT FK_HOA_DON_KHACH FOREIGN KEY (MA_KHACH_MUA) REFERENCES KHACH(MA_KH)
)

CREATE TABLE MAT_HANG(
MA_MH VARCHAR(50) NOT NULL,
TEN_MH VARCHAR(50) NOT NULL,
GIA NUMERIC(20) NOT NULL,
MA_NCC VARCHAR(50) NOT NULL,
STT_GH CHAR(3) NULL,
CONSTRAINT PK_MAT_HANG PRIMARY KEY (MA_MH),
CONSTRAINT FK_MAT_HANG_NHA_CUNG_CAP FOREIGN KEY (MA_NCC) REFERENCES NHA_CUNG_CAP(MA_NCC),
CONSTRAINT FK_MAT_HANG_GIAN_HANG FOREIGN KEY(STT_GH) REFERENCES GIAN_HANG(STT_GH)
)

CREATE TABLE CT_HOADON(
MA_HD VARCHAR(50) NOT NULL,
MA_MH VARCHAR(50) NOT NULL,
SO_LUONG INT NULL,
GIA numeric NULL,
CONSTRAINT PK_CT_HOADON PRIMARY KEY (MA_MH,MA_HD),
CONSTRAINT FK_CT_HOADON_HOA_DON FOREIGN KEY (MA_HD) REFERENCES HOA_DON(MA_HD),
CONSTRAINT FK_CT_HOADON_MAT_HANG FOREIGN KEY(MA_MH) REFERENCES MAT_HANG(MA_MH)
)
